#!/bin/bash

set -e

./usage 1 "orderly project disconnect <project-id>" "$@"

project_id=$1

if ! ./orderly-project-is-connected $project_id; then
	./error "orderly: project already disconnected."
fi

cd $(./orderly-path $project_id)
git remote remove origin

