#!/bin/bash

set -e

./usage 2 "orderly project connect <project-id> <repository>" "$@"

project_id=$1
repository=$2

./orderly-project-exists $project_id

if ./orderly-project-is-connected $project_id; then
	./error "orderly: project already connected."
fi

project_path=$(./orderly-path $project_id)

cd $project_path
git remote add origin $repository
git fetch --quiet

if [ $(git branch -r | wc -w) -eq 0 ]; then
	git commit --quiet --allow-empty -m "Create project."
else
	git pull origin master --quiet > /dev/null
fi

git push origin master --quiet

