#!/bin/bash

set -e

./usage 3 "orderly-asset-destroy <project-id> <asset-type> <asset-id>" "$@"

project_id=$1
asset_type=$2
asset_id=$3

./orderly-project-assert-exists $project_id

if ! ./orderly-asset-exists $project_id $asset_type $asset_id; then
	./error "orderly: '$asset_id' asset does not exist."
fi

asset_path=$(./orderly-path $project_id $asset_type $asset_id)

rm $asset_path

./orderly-write $asset_path "Destroy $asset_type $asset_id."

