#!/bin/bash

set -e

./usage 3 "sam-asset-destroy <project-id> <asset-type> <asset-id>" "$@"

project_id=$1
asset_type=$2
asset_id=$3

./sam-project-assert-exists $project_id

if ! ./sam-asset-exists $project_id $asset_type $asset_id; then
	./error "sam: '$asset_id' asset does not exist."
fi

asset_path=$(./sam-path $project_id $asset_type $asset_id)

rm $asset_path

./sam-write $asset_path "Destroy $asset_type $asset_id."
