#!/bin/bash

set -e

./usage 1 "orderly project create <project-id> [repository]" "$@"

project_id=$1
repository=$2

project_path=$(./orderly-path $project_id)

if ./orderly-project-exists $project_id; then
	./error "orderly: project '$project_id' already exists."
fi

mkdir -p $project_path
cd $project_path
git init --quiet
cd - > /dev/null

if [ ! -z "$repository" ]; then
	./orderly-project-connect $project_id $repository
fi

