#!/bin/bash

set -e

./usage 3 "orderly asset create <project-id> <asset-type> <asset-id>" "$@"

project_id=$1
asset_type=$2
asset_id=$3

./orderly-project-assert-exists $project_id

if ./orderly-asset-exists $project_id $asset_type $asset_id; then
	./error "orderly: '$asset_id' asset already exists."
fi

data=$(cat)
asset_path=$(./orderly-path $project_id $asset_type $asset_id)

if [ ! -d $(dirname $asset_path) ]; then
	mkdir -p $(dirname $asset_path)
fi

echo "$data" > $asset_path

./orderly-write $asset_path "Create $asset_type $asset_id."

