#!/bin/bash

set -e

version=0.1.1

usage() {
	echo "Software Asset Manager, version $version"
	echo "usage: sam [--help] [--version] <command> [<arguments>]"
	echo
	echo "Supported commands are:"
	echo "asset       Manage assets"
	echo "install     Installs sam to /usr/local/bin"
	echo "project     Manage projects"
	echo "uninstall   Uninstalls sam from /usr/local/bin"
	echo
}

if [ $# -lt 1 ]; then
	usage >&2
	exit 1
fi

command=$1
cd $(dirname $(readlink -f $0))

case $command in
	asset)
		./sam-asset "${@:2}"
		;;

	install)
		./sam-install "${@:2}"
		;;

	project)
		./sam-project "${@:2}"
		;;

	uninstall)
		./sam-uninstall "${@:2}"
		;;

	--help)
		usage
		;;

	--version)
		echo "sam version 0.1.0"
		exit 0
		;;

	*)
		echo "sam: '$command' is not a sam command." >&2
		echo >&2
		usage >&2
		exit 1
esac
