#!/bin/bash

set -e

./usage 1 "sam project disconnect <project-id>" "$@"

project_id=$1

if ! ./sam-project-is-connected $project_id; then
	./error "sam: project already disconnected."
fi

cd $(./sam-path $project_id)
git remote remove origin
