#!/bin/bash

set -e

./usage 0 "sam-path <project-id> <asset-type> [<asset-id>]" "$@"

project_id=$1
asset_type=$2
asset_id=$3

sam_home=~/.sam

if [ $# -eq 0 ]; then
	echo "$sam_home/project"
elif [ $# -eq 1 ]; then
	echo "$sam_home/project/$project_id"
elif [ $# -eq 2 ]; then
	echo "$sam_home/project/$project_id/$asset_type"
else
	echo "$sam_home/project/$project_id/$asset_type/$asset_id"
fi
