#!/bin/bash

set -e

./usage 1 "sam project is-connected <project-id>" "$@"

project_id=$1

./sam-project-exists $project_id

project_path=$(./sam-path $project_id)

cd $project_path
if [ $(git remote | wc -w) -eq 0 ]; then
	exit 1
fi
