#!/bin/bash

set -e

./usage 1 "sam project create <project-id>" "$@"

project_id=$1

project_path=$(./sam-path $project_id)

if ./sam-project-exists $project_id; then
	./error "sam: project '$project_id' already exists."
fi

mkdir -p $project_path
cd $project_path
git init --quiet
cd - > /dev/null
